apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  labels:
    app: go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: 183295423434.dkr.ecr.ap-south-1.amazonaws.com/goapp:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
      imagePullSecrets:
          - name: regcred
  
